CREATE TABLE [dbo].[PC_CONFIG]
(
[PROCESS_CODE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STEP_CODE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STEP_NAME] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ASSEMBLY_NAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FORM_NAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
