CREATE TABLE [dbo].[CM_COUNTRY_MASTER]
(
[COUNTRY_CODE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COUNTRY_NAME] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CM_COUNTRY_MASTER] ADD CONSTRAINT [PK_CM_COUNTRY_MASTER] PRIMARY KEY CLUSTERED  ([COUNTRY_CODE]) ON [PRIMARY]
GO
